
server:
  port: 8084


eureka:
  instance:
    # 此项不填时会造成通过本地域名访问 feign 从而 404
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka
      #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）
      #租约续订间隔时间（默认30秒），如下所示每间隔 5s 向服务端发送一次心跳，证明自己依然"存活"
      lease-renewal-interval-in-seconds: 3 # 5秒一次心跳
      #Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
      # 租约到期时间（默认90秒），如下所示，告诉服务端如果我 6s 之内没有给你发心跳，就代表我"死"了，将我踢出掉
      lease-expiration-duration-in-seconds: 6

spring:
  application:
    name: repeat